name: build and deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    name: build and deploy gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: use node.js@14
        uses: actions/setup-node@main
        with:
          node-version: 14

      - name: build
        run: |
          yarn
          yarn build

      - name: deploy gh-pages
        run: |
          cd build
          echo "excalidraw.dongfg.com" > CNAME
          git init
          git config --local user.name dongfg
          git config --local user.email mail@dongfg.com
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy gh-pages"
          git push origin gh-pages -f
